import type { NextPage } from "next";
import Head from "next/head";

import Skills from "../components/skills";
import Works from "../components/works";

import { Inter } from "next/font/google";
import Hero from "../components/Hero";

import Blog from "../components/Blog";
import Marketing from "../components/Marketing";

import Timeline from "../components/Timeline";
import CardList from "../components/CardList";
import ContactUsMap from "../components/ContactUsMap";
import InfiniteScroll from "../components/InfiniteScroll";
import HorizontalTimeline from "../components/Services/HorizontalTimeline";
import VerticalTimeline from "../components/Services/VerticalTimeline";
import BuildingBlock from "../components/BuildingBlock";
import Button from "../components/Button";
import ButtonGlowHover from "../components/ButtonGlowHover";
// const inter = Inter({ subsets: ["latin"] });
import Member from "../components/member";
import Hero2 from "../components/Hero2";
import Hero3 from "../components/Hero3";
import Jobs2 from "../components/Jobs2";
import CardMobile from "../components/CardMobile";
import CardInteractive from "../components/CardInteractive";

const Home = () => {
  return (
    <div className="bg-[#0d0e11] ">
      <Head>
        <title>GUTUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero /> */}
      {/* <Member/> */}
      {/* <ButtonGlowHover/> */}
      {/* <Hero /> */}
      <Hero3 />
      {/* <Jobs2 /> */}
      <div className=" hidden md:block">
        <CardInteractive />
      </div>
      {/* <CardInteractive /> */}
      <div className="block md:hidden ">
        <CardMobile />
      </div>
      {/* <CardInteractive /> */}

      <Skills />
      {/* <CardList /> */}
      <div className="mx-auto text-center mb-10">
        {/* <Button href="/services" content="Vezi Toate" /> */}
      </div>
      <Works />

      <div className="md:pt-[130px] pt-[70px]">
        <BuildingBlock />
        <HorizontalTimeline />
      </div>
      <VerticalTimeline />
      {/* <Marketing /> */}
      <Blog />
      {/* <ContactUsMap /> */}
    </div>
  );
};

export default Home;
