import type { NextPage } from "next";
import Head from "next/head";

import Skills from "../components/skills";
import Works from "../components/works";

import { Inter } from "next/font/google";
import Hero from "../components/Hero";

import Blog from "../components/Blog";
import Marketing from "../components/Marketing";

import Timeline from "../components/Timeline";
import CardList from "../components/CardList";
import ContactUsMap from "../components/ContactUsMap";
const inter = Inter({ subsets: ["latin"] });
const Home: NextPage = () => {
  return (
    <div className={inter.className}>
      <Head>
        <title>GUTUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />

      <CardList />

      <Skills />
      <Works />
      <Timeline />

      <Marketing />

      <Blog />

      <ContactUsMap />
    </div>
  );
};

export default Home;
